### ISSUE TITLE
ubuntu22.04にKaggle clientをインストールする方法が分からない

### ISSUE THREAD

**Issue by tacsotai** [smly/kaggle-book-gokui#10]
以下コマンドを叩くのはいいのだが、依存性モジュールがないだとどうの言われてそれを解決するものが欲しい。
環境はUbuntu22.04 server on lxd.
```
pip install kaggle-cli
```

**Comment by tacsotai** [comment]
Installing collected packages: lxml, beautifulsoup4, python-utils, pbr, cssselect, configparser, cmd2, stevedore, progressbar2, MechanicalSoup, cliff, kaggle-cli
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [775 lines of output]
      Building lxml version 4.0.0.

**Comment by upura** [comment]
https://github.com/floydwch/kaggle-cli/issues/79 に同様の issue がありました。lxml のバージョン指定を外すことで上手くいった事例があるようです。

**Comment by smly** [comment]
kaggle-cli は初めて知りました。名前が紛らわしいですがこちらはパスワードを平文で扱う非公式ツールであるため、kaggle 公式の CLI ツールの利用をお勧めします。公式ツールは kaggle のアカウントページから発行したトークンによって認証を行うため、より安全です。

```
pip install kaggle
```

**Comment by tacsotai** [comment]
ありがとうございます。そもそも
```
pip install kaggle-cli
```
ではなく
```
pip install kaggle
```
を使用するということで了解しました。本Issueは閉じさせていただきます。

**Comment by smly** [comment]
ご質問いただきありがとうございました！分かりづらい点など参考になり助かります。
