### ISSUE TITLE
3.7.2 TTAにおける説明文について

### ISSUE THREAD

**Issue by KIrie-0217** [smly/kaggle-book-gokui#15]
p82 3.7.2 test time augmentationにて
５行目

> TTAでは、その名の通り、検証データや**テキストデータ**の

と記載されておりますが、こちらは**テストデータ**の誤表記でしょうか？

上記の認識が正しいかご教示いただけますと幸いです。
よろしくお願いいたします。

**Comment by upura** [comment]
ご連絡ありがとうございます。仰る通りです。正誤表に追加し、次回以降の版で訂正いたします。
