### ISSUE TITLE
p101　１行目　extract_features()?

### ISSUE THREAD

**Issue by projectGGG** [smly/kaggle-book-gokui#23]
「ファイルリストから特徴表現を抽出する関数をextract_features()と定義し、」
とありますが、それはどこで定義していますか？
extract_vectors()ならありますが。

よろしくお願いします。

**Comment by smly** [comment]
@projectGGG ご報告いただきありがとうございます！ご指摘のとおり関数名は`extract_features()` は誤りであり、正しくは `extract_vectors()` でした。正誤表に追記し、次回の改訂時に修正対応いたします。
