### ISSUE TITLE
p149 次元削減に基づく古典的な手法

### ISSUE THREAD

**Issue by momijiame** [smly/kaggle-book-gokui#26]
文中に ``negative matrix factorization (NMF)`` とありますが ``non-negative matrix factorization (NMF)`` でしょうか？
確認したのは第 1 刷です。

**Comment by upura** [comment]
ご連絡ありがとうございます。最新の第 4 刷でも未対応でした。#27 で正誤表を更新し、次回改訂時に対応いたします。
