### ISSUE TITLE
p.101 本文2行目

### ISSUE THREAD

**Issue by suk1yak1** [smly/kaggle-book-gokui#3]
mAP@kによって検索結果を評価する関数が`extract_vectors`になっていますが、`compute_map_and_print`ではないでしょうか？

**Comment by smly** [comment]
本を読んで頂きありがとうございます！またご報告いただきありがとうございます。ご指摘のとおり関数名は `compute_map_and_print` が正しいものでした。正誤表に追記し、次回の改訂時に修正対応いたします。

**Comment by suk1yak1** [comment]
早々にご確認いただきありがとうございます！
Kaggleだけでなく実務にも役立ちそうなtipsが盛りだくさんなので熟読させて頂きます
