### ISSUE TITLE
p197 参考文献の参照がずれていそう

### ISSUE THREAD

**Issue by karunru** [smly/kaggle-book-gokui#31]
第一刷 p197  `より効果的だったのは`~ `計算するという方法でした^{[263]}。`
の[263] は https://github.com/smly/kaggle-book-gokui/blob/main/references.md?plain=1#L267 の https://huggingface.co/docs/transformers/preprocessing ですが，文脈的にGoogle QUEST Q&A Labelingの何らかの解法のdiscussion であるように思われます．
こちらの参照は正しいものでしょうか？

**Comment by upura** [comment]
ご報告いただき、ありがとうございます。仰る通りで [263] ではなく [266] が正しい参照番号です。正誤表に追加し、次回以降の版で訂正いたします。
https://github.com/smly/kaggle-book-gokui/blob/main/references.md?plain=1#L270

**Comment by karunru** [comment]
ご回答ありがとうございます！よろしくお願いいたします．
