### ISSUE TITLE
p.21の損失収束のグラフに関しての質問

### ISSUE THREAD

**Issue by karaage0703** [smly/kaggle-book-gokui#6]
本のコードの通り学習させてみたのですが、書籍のグラフのようにうまく収束しませんでした。

![sgd](https://user-images.githubusercontent.com/5562157/216795426-f073a296-cec9-4524-8244-eaf1068b6b5b.png)

試しに以下の通りOptimizerをSGD -> Adamに変更したら書籍の収束に近くなりました。

```
optimizer = optim.Adam(model.parameters(), lr=0.01)
#optimizer = optim.SGD(model.parameters(), lr=0.01)
```

![adam](https://user-images.githubusercontent.com/5562157/216795455-aaf705b3-cf42-45fd-b669-3f47cf8e5dfb.png)

書籍のように収束させるには、コードの変更が必要なように感じました。疑問に思う人がいるかもしれないので質問させていただきました。

**Comment by upura** [comment]
ご連絡ありがとうございます。結論から申し上げると、コードには誤りがなく、書籍の説明に意図通りではない箇所がありました。損失が単調に減少する傾向には変わりがなく、本文の流れに大きな影響はない認識ですが、おっしゃる通り疑問に思う方がいそうです。

以下の訂正 2 点を、次回に反映予定です。

## 訂正点 1: 画像の差し替えもしくは説明の変更

p. 21「図2.3　損失の収束の可視化」には `fig00.png` を掲載すべきところ、その次のミニバッチの処理も取り込んだ結果である `fig01.png` が掲載されていました。次のいずれかの対応を予定しています。

- `fig00.png` を `fig01.png` に差し替える
- 図2.3 が p.22 のミニバッチの処理も取り込んだ可視化結果である旨を追記する

https://github.com/smly/kaggle-book-gokui/blob/7481194178c79af961f5b9047eb710fffa073531/chapter2/00_mlp.py#L65

https://github.com/smly/kaggle-book-gokui/blob/7481194178c79af961f5b9047eb710fffa073531/chapter2/01_mlp_batch.py#L90

## 訂正点 2: 図番号の修正

p. 21「図 2.4 のように可視化されます」を「図 2.3 のように可視化されます」に修正します。

**Comment by karaage0703** [comment]
@upura 
早速の回答ありがとうございます。

書籍の通りミニバッチ処理を実施することで、書籍の通りの結果になることを確認できました。

![batch](https://user-images.githubusercontent.com/5562157/216805346-9c96c91b-2fdf-4768-8b3c-fcd10118d3f3.jpg)

`batch_size=1797`とすると、当たり前ですがミニバッチ処理無しと同じ結果になりました。

![batch_size_1797](https://user-images.githubusercontent.com/5562157/216806074-63becdbb-1c97-48c8-a4fa-d96963e26adb.jpg)

バッチサイズと性能と学習時間の関係、あんまり意識して比較したことなかったので理解深まりました。
